In [1]:
import pandas as pd

In [8]:
teamrating = pd.read_csv('23-24TeamRatings.csv')
teamrating.head()

,Rk,Team,Conf,Div,W,L,W/L%,MOV,ORtg,DRtg,NRtg,MOV/A,ORtg/A,DRtg/A,NRtg/A
0,1,Boston Celtics,E,A,64,18,0.780,11.34,124.23,112.51,11.71,10.74,123.81,112.70,11.11
1,2,Oklahoma City Thunder,W,NW,57,25,0.695,7.41,120.43,113.12,7.31,7.36,120.49,113.23,7.26
2,3,Minnesota Timberwolves,W,NW,56,26,0.683,6.45,116.63,109.98,6.65,6.38,116.53,109.95,6.57
3,4,Denver Nuggets,W,NW,57,25,0.695,5.26,119.49,114.05,5.44,5.23,119.60,114.20,5.40
4,5,New York Knicks,E,A,50,32,0.610,4.59,119.11,114.22,4.89,4.36,118.93,114.28,4.66

In [39]:
teamadvanced = pd.read_csv('23-24TeamAdvanceStats.csv')
teamadvanced = teamadvanced.drop(columns=['Unnamed: 22', 'Unnamed: 27'])
teamadvanced['Team'] = teamadvanced['Team'].str.replace('*', '', regex=False).str.strip()
teamadvanced.rename(columns={
    'eFG%.1': 'eFG%',
    'TOV%.1': 'TOV%',
    'FT/FGA.1': 'Opponent FT/FGA'
}, inplace=True)
teamadvanced = teamadvanced[teamadvanced['Team'] != 'League Average']
teamadvanced.head(31)
teamadvanced.dtypes

#teamadvanced.to_csv('Cleaned_TeamAdvancedStats.csv', index=False)

Rk                 float64
Team                object
Age                float64
W                  float64
L                  float64
PW                   int64
PL                   int64
MOV                float64
SOS                float64
SRS                float64
ORtg               float64
DRtg               float64
NRtg               float64
Pace               float64
FTr                float64
3PAr               float64
TS%                float64
Unnamed: 17        float64
eFG%               float64
TOV%               float64
ORB%               float64
FT/FGA             float64
eFG%               float64
TOV%               float64
DRB%               float64
Opponent FT/FGA    float64
Arena               object
Attend.              int64
Attend./G            int64
dtype: object

In [76]:
shootingtypes= pd.read_csv('23-24ShootingTypePerTeamStats.csv')
shootingtypes = shootingtypes.drop(columns=[ 'Unnamed: 13',
    'Unnamed: 6', 'Unnamed: 26', 'Unnamed: 29', 'Unnamed: 32', 'Unnamed: 23','Unnamed: 20'
])
shootingtypes['Team'] = shootingtypes['Team'].str.replace('*', '', regex=False).str.strip()
shootingtypes.rename(columns={
    '10-Mar': '3-10',
    '16-Oct': '10-16',
    '2P.1':'2PFGM%',
    '0-3.1': '0-3FGM%',
    '10-Mar.1':'3-10FGM%',
    'Att.':'Heaves Attempt',
    '16-Oct.1':'10-16PFGM%',
    '16-3P.1':'16-3PFGM%',
    '3P.1':'3PFGM%',
    '2P.2':'%Astd2P',
    '3P.2':'%Asted3P',
    '%FGA':'%FGDunks',
    'Md.':'TotalDunksMade',
    '%FGA.1':'%FGLayups',
    'Md..1':'TotalLayups',
    '3%PA':'%Corner3PA',
    '3P%':'3P%Corner',
    'Md..2': 'Heaves Made'
}, inplace=True)
shootingtypes.dtypes
#shootingtypes.to_csv('Cleaned_ShootingTypeStats.csv', index=False)

Rk                  int64
Team               object
G                   int64
MP                  int64
FG%               float64
Dist.             float64
2P                float64
0-3               float64
3-10              float64
10-16             float64
16-3P             float64
3P                float64
2PFGM%            float64
0-3FGM%           float64
3-10FGM%          float64
10-16PFGM%        float64
16-3PFGM%         float64
3PFGM%            float64
%Astd2P           float64
%Asted3P          float64
%FGDunks          float64
TotalDunksMade      int64
%FGLayups         float64
TotalLayups         int64
%3PA              float64
3P%Corner         float64
Heaves Attempt      int64
Heaves Made         int64
dtype: object

In [82]:
teamstats = pd.read_csv('23-24TeamPerGameStats.csv')
teamstats['Team'] = teamstats['Team'].str.replace('*', '', regex=False).str.strip()
teamstats = teamstats.iloc[:-1]
teamstats.head(32)
teamstats.to_csv('Cleaned_TeamStats.csv', index=False)

In [12]:
player_info = pd.read_csv('../../data/rawdata/PlayerInfo.csv')



def height_wingspan_to_inches(measurement_str):
    """Converts a string like "F'I.XX\"" (e.g., "6'11.25\"") to total inches."""
    # Handle missing data (like NaN in the Team column showing up if parsing was imperfect)
    if pd.isna(measurement_str) or not isinstance(measurement_str, str):
        return np.nan # Return Not a Number for missing values
    
    try:
        # Split the string at the foot marker (')
        parts = measurement_str.split("'")
        feet = int(parts[0])
        
        # Remove the inch marker (") and convert the inches part to a float
        inches = float(parts[1].replace('"', ''))
        
        # Calculate total inches
        total_inches = (feet * 12) + inches
        return total_inches
    except (IndexError, ValueError):
        # Handle cases where the string format might be unexpected
        print(f"Warning: Could not parse '{measurement_str}'. Returning NaN.")
        return np.nan

# Apply the conversion function to the 'Height' column
player_info['Height_Inches'] = player_info['Height'].apply(height_wingspan_to_inches)

# Apply the conversion function to the 'Wingspan' column
player_info['Wingspan_Inches'] = player_info['Wingspan'].apply(height_wingspan_to_inches)

columns = ['Player', 'Team', 'Position', 'Height_Inches', 'Wingspan_Inches']

player_info_cleaned = player_info[columns]

player_info_cleaned.to_csv('../../data/cleandata/Cleaned_PlayerInfo.csv')

In [43]:
cleaned_player_length = pd.read_csv('../../data/cleandata/Cleaned_PlayerInfo.csv')
cleaned_player_length

raw_player_minutes = pd.read_csv('../../data/rawdata/PlayerMinutes.csv')
raw_player_minutes

player_merged_data = pd.merge(
        cleaned_player_length,
        raw_player_minutes[['PLAYER_NAME', 'TEAM_ABBREVIATION', 'MIN']], # Select only the needed columns from the minutes data
        left_on=['Player', 'Team'],           # Columns from cleaned_player_length
        right_on=['PLAYER_NAME', 'TEAM_ABBREVIATION'], # Columns from raw_player_minutes
        how='left'                             # Keep all rows from the left dataframe
    )
player_merged_data = player_merged_data.drop(columns=['PLAYER_NAME', 'TEAM_ABBREVIATION'])

columns = ['Player', 'Team', 'Position', 'Height_Inches', 'Wingspan_Inches', 'MIN']
player_merged_data = player_merged_data[columns]
player_merged_data.dropna(subset=['MIN'], inplace=True) 
player_merged_data = player_merged_data[player_merged_data['MIN'] > 0].copy()

player_merged_data.to_csv('../../data/cleandata/Cleaned_PlayerMinutesLength', index=False)

In [44]:
player_merged_data['H_x_MP'] = player_merged_data['Height_Inches'] * player_merged_data['MIN']

team_grouped = player_merged_data.groupby('Team') 

team_agg_h = team_grouped.agg(
    Total_MP_H=('MIN', 'sum'),
    Sum_H_x_MP=('H_x_MP', 'sum')
)
team_agg_h['Avg_Height_Weighted'] = team_agg_h['Sum_H_x_MP'] / team_agg_h['Total_MP_H']


player_data_ws = player_merged_data.dropna(subset=['Wingspan_Inches']).copy()

player_data_ws['WS_x_MP'] = player_data_ws['Wingspan_Inches'] * player_data_ws['MIN']

team_grouped_ws = player_data_ws.groupby('Team') # Group again on the filtered data

team_agg_ws = team_grouped_ws.agg(
    Total_MP_WS=('MIN', 'sum'),
    Sum_WS_x_MP=('WS_x_MP', 'sum')
)
team_agg_ws['Avg_Wingspan_Weighted'] = team_agg_ws['Sum_WS_x_MP'] / team_agg_ws['Total_MP_WS']

# --- Combine height and wingspan averages ---
team_weighted_stats = pd.merge(
    team_agg_h[['Avg_Height_Weighted']], 
    team_agg_ws[['Avg_Wingspan_Weighted']], 
    left_index=True,  # Merge on Team index from groupby
    right_index=True, 
    how='left'         # Keep all teams, even if they lack wingspan data (will have NaN)
)

team_weighted_stats.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, ATL to WAS
Data columns (total 2 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Avg_Height_Weighted    30 non-null     float64
 1   Avg_Wingspan_Weighted  30 non-null     float64
dtypes: float64(2)
memory usage: 720.0+ bytes

In [61]:
team_shot_zones = pd.read_csv('../../data/cleandata/Cleaned_2024-2025TeamShotZones.csv')
team_shot_zones.head()

,TEAM,RestrictedArea_FGM,RestrictedArea_FGA,RestrictedArea_FG%,InThePaintNonRA_FGM,InThePaintNonRA_FGA,InThePaintNonRA_FG%,MidRange_FGM,MidRange_FGA,MidRange_FG%,...,LeftCorner3_FG%,RightCorner3_FGM,RightCorner3_FGA,RightCorner3_FG%,Corner3_FGM,Corner3_FGA,Corner3_FG%,AboveTheBreak3_FGM,AboveTheBreak3_FGA,AboveTheBreak3_FG%
0,Atlanta Hawks,18.1,27.7,65.2,9.5,20.9,45.6,2.3,5.5,41.1,...,40.0,2.5,6.0,41.0,4.4,10.8,40.6,9.1,26.6,34.2
1,Boston Celtics,14.5,20.6,70.6,6.1,13.4,45.4,3.2,7.8,41.5,...,37.1,1.9,4.8,40.8,3.7,9.6,38.9,14.0,38.5,36.5
2,Brooklyn Nets,15.3,24.5,62.6,6.5,16.7,38.6,2.3,5.5,41.7,...,33.4,2.0,5.6,35.9,3.8,10.9,34.7,9.8,28.3,34.5
3,Charlotte Hornets,15.3,24.4,62.6,7.2,18.8,38.3,2.8,7.5,37.6,...,36.3,1.6,4.3,38.0,3.5,9.4,37.1,9.5,28.6,33.1
4,Chicago Bulls,17.6,28.0,63.0,7.8,15.5,49.9,2.4,6.4,37.1,...,42.4,1.6,4.8,34.3,4.2,10.8,38.8,11.2,31.1,36.1

In [62]:
team_name_to_abbr = {
    'Atlanta Hawks': 'ATL', 
    'Boston Celtics': 'BOS', 
    'Brooklyn Nets': 'BKN',
    'Charlotte Hornets': 'CHA', 
    'Chicago Bulls': 'CHI', 
    'Cleveland Cavaliers': 'CLE',
    'Dallas Mavericks': 'DAL', 
    'Denver Nuggets': 'DEN', 
    'Detroit Pistons': 'DET',
    'Golden State Warriors': 'GSW', 
    'Houston Rockets': 'HOU', 
    'Indiana Pacers': 'IND',
    'LA Clippers': 'LAC',  # Check if your shot zones uses 'LA Clippers' or 'Los Angeles Clippers'
    'Los Angeles Lakers': 'LAL', 
    'Memphis Grizzlies': 'MEM',
    'Miami Heat': 'MIA', 
    'Milwaukee Bucks': 'MIL', 
    'Minnesota Timberwolves': 'MIN',
    'New Orleans Pelicans': 'NOP', 
    'New York Knicks': 'NYK', 
    'Oklahoma City Thunder': 'OKC',
    'Orlando Magic': 'ORL', 
    'Philadelphia 76ers': 'PHI', 
    'Phoenix Suns': 'PHX',
    'Portland Trail Blazers': 'POR', 
    'Sacramento Kings': 'SAC', 
    'San Antonio Spurs': 'SAS',
    'Toronto Raptors': 'TOR', 
    'Utah Jazz': 'UTA', 
    'Washington Wizards': 'WAS'
    # Add/modify any names based on the exact strings in your 'TEAM' column
}

team_shot_zones['TeamAbbreviation'] = team_shot_zones['TEAM'].map(team_name_to_abbr)

In [65]:
final_team_stats = pd.merge(
    team_weighted_stats,      # Left DataFrame (Index: Team Abbreviation)
    team_shot_zones,          # Right DataFrame
    left_index=True,          
    right_on='TeamAbbreviation', 
    how='left'                # Keep all teams from team_weighted_stats
)


columns = ['TEAM', 'TeamAbbreviation', 'Avg_Height_Weighted', 'Avg_Wingspan_Weighted', 
       'RestrictedArea_FGA', 'InThePaintNonRA_FGA', 'MidRange_FGA', 'Corner3_FGA', 'AboveTheBreak3_FGA'] 
final_team_stats=final_team_stats[columns]
final_team_stats['3_FGA'] = final_team_stats['Corner3_FGA'] + final_team_stats['AboveTheBreak3_FGA']
final_team_stats['total_FGA'] = final_team_stats['3_FGA'] + final_team_stats['RestrictedArea_FGA'] + final_team_stats['InThePaintNonRA_FGA'] + 
final_team_stats

,TEAM,TeamAbbreviation,Avg_Height_Weighted,Avg_Wingspan_Weighted,RestrictedArea_FGA,MidRange_FGA,Corner3_FGA,AboveTheBreak3_FGA,3_FGA
0,Atlanta Hawks,ATL,78.199084,82.260554,27.7,5.5,10.8,26.6,37.4
2,Brooklyn Nets,BKN,78.558651,82.452738,24.5,5.5,10.9,28.3,39.2
1,Boston Celtics,BOS,78.357433,82.241503,20.6,7.8,9.6,38.5,48.1
3,Charlotte Hornets,CHA,78.559888,82.751105,24.4,7.5,9.4,28.6,38.0
4,Chicago Bulls,CHI,78.457277,82.040728,28.0,6.4,10.8,31.1,41.9
5,Cleveland Cavaliers,CLE,77.461218,82.050649,25.2,7.1,10.6,30.7,41.3
6,Dallas Mavericks,DAL,77.929672,83.165571,24.1,9.9,9.3,24.6,33.9
7,Denver Nuggets,DEN,78.779310,82.386451,30.1,9.7,7.2,24.2,31.4
8,Detroit Pistons,DET,77.373913,82.795024,26.5,8.5,8.8,26.4,35.2
9,Golden State Warriors,GSW,76.821493,81.454978,22.3,7.7,10.6,31.5,42.1
10,Houston Rockets,HOU,77.713618,81.414022,27.1,10.3,7.8,27.9,35.7
11,Indiana Pacers,IND,78.062798,82.810047,24.6,11.2,9.3,26.2,35.5
12,LA Clippers,LAC,78.226662,83.533351,23.8,7.8,8.2,25.1,33.3
13,Los Angeles Lakers,LAL,78.992336,83.377106,23.5,8.7,9.1,27.0,36.1
14,Memphis Grizzlies,MEM,79.413490,82.088972,24.5,6.1,10.0,27.6,37.6
15,Miami Heat,MIA,77.741392,82.124133,22.5,7.4,11.1,26.1,37.2
16,Milwaukee Bucks,MIL,79.144568,83.601567,23.9,12.8,9.3,27.2,36.5
17,Minnesota Timberwolves,MIN,78.084884,83.132049,25.1,6.4,10.5,29.1,39.6
18,New Orleans Pelicans,NOP,77.637181,81.173282,27.0,9.0,9.1,25.5,34.6
19,New York Knicks,NYK,76.873735,82.421782,27.9,10.2,10.2,23.7,33.9
20,Oklahoma City Thunder,OKC,77.217104,82.575736,24.3,10.1,8.7,30.1,38.8
21,Orlando Magic,ORL,78.996672,82.175792,24.3,10.1,9.8,25.1,34.9
22,Philadelphia 76ers,PHI,77.284683,82.811034,26.7,8.7,8.0,28.9,36.9
23,Phoenix Suns,PHX,77.558732,82.047788,16.1,11.8,11.8,26.1,37.9
24,Portland Trail Blazers,POR,78.697330,84.004655,29.6,7.6,9.5,28.0,37.5
25,Sacramento Kings,SAC,78.389853,81.910321,20.3,15.0,8.5,26.5,35.0
26,San Antonio Spurs,SAS,77.756008,82.176008,27.2,9.1,10.3,29.0,39.3
27,Toronto Raptors,TOR,78.048374,83.408784,30.0,7.8,10.1,23.6,33.7
28,Utah Jazz,UTA,78.318139,81.362965,20.5,6.4,11.4,28.3,39.7
29,Washington Wizards,WAS,77.929945,82.394090,23.8,8.5,7.0,31.9,38.9

In [64]:
team_totals = pd.read_csv('../../data/rawdata/2024-2025TeamTotals.csv', index_col=False)
team_totals

/tmp/ipykernel_1895338/393385037.py:1: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  team_totals = pd.read_csv('../../data/rawdata/2024-2025TeamTotals.csv', index_col=False)

,TEAM,GP,W,L,WIN%,MIN,PTS,FGM,FGA,FG%,...,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,+/-
0,Oklahoma City Thunder,82,68,14,0.829,3941,9881,3660,7600,48.2,...,2801,3672,2220,296,184,746,539,216,311,485
1,Cleveland Cavaliers,82,64,18,0.780,3951,9999,3652,7444,49.1,...,2806,3723,2304,1082,670,350,361,1487,1553,782
2,Boston Celtics,82,61,21,0.744,3966,9534,3413,7382,46.2,...,2783,3716,2144,973,589,452,295,1303,1438,747
3,Minnesota Timberwolves,82,49,33,0.598,3966,9372,3364,7182,46.8,...,2726,3634,2142,1186,654,406,368,1498,1571,410
4,Memphis Grizzlies,82,48,34,0.585,3941,9980,3670,7654,47.9,...,2819,3875,2330,1285,726,462,450,1711,1653,398
5,LA Clippers,82,50,32,0.610,3961,9256,3409,7075,48.2,...,2750,3591,2064,1220,773,370,352,1503,1458,382
6,Houston Rockets,82,52,30,0.634,3956,9372,3484,7659,45.5,...,2774,3974,1914,1139,689,411,467,1557,1577,370
7,New York Knicks,82,51,31,0.622,3976,9494,3553,7315,48.6,...,2607,3497,2254,1088,671,324,406,1407,1554,336
8,Denver Nuggets,82,50,32,0.610,3971,9902,3724,7360,50.6,...,2832,3751,2542,1169,656,402,420,1444,1562,319
9,Golden State Warriors,82,48,34,0.585,3946,9331,3342,7412,45.1,...,2692,3721,2386,1152,771,391,441,1571,1523,271
10,Milwaukee Bucks,82,48,34,0.585,3951,9472,3445,7082,48.6,...,2882,3556,2090,1097,601,384,315,1469,1552,203
11,Indiana Pacers,82,50,32,0.610,3971,9624,3574,7326,48.8,...,2678,3430,2398,1082,694,448,366,1533,1541,183
12,Detroit Pistons,82,44,38,0.537,3961,9471,3503,7363,47.6,...,2739,3670,2165,1218,652,431,413,1695,1551,156
13,Los Angeles Lakers,82,50,32,0.610,3946,9298,3356,7007,47.9,...,2687,3479,2131,1145,633,367,344,1415,1576,100
14,Miami Heat,82,37,45,0.451,3986,9069,3318,7138,46.5,...,2760,3558,2166,1114,668,314,438,1527,1390,46
15,Sacramento Kings,82,40,42,0.488,3976,9490,3529,7385,47.8,...,2723,3624,2169,1092,620,357,350,1548,1515,39
16,Orlando Magic,82,41,41,0.500,3946,8645,3130,7036,44.5,...,2517,3431,1887,1165,729,488,361,1648,1666,-10
17,Atlanta Hawks,82,40,42,0.488,3956,9691,3556,7528,47.2,...,2675,3649,2426,1273,798,419,403,1564,1563,-93
18,Dallas Mavericks,82,39,43,0.476,3946,9364,3443,7194,47.9,...,2702,3530,2070,1151,636,445,375,1458,1532,-98
19,Chicago Bulls,82,39,43,0.476,3951,9660,3543,7545,47.0,...,2935,3760,2383,1203,621,386,417,1444,1374,-128
20,San Antonio Spurs,82,34,48,0.415,3946,9342,3426,7362,46.5,...,2685,3581,2348,1138,673,455,356,1363,1428,-226
21,Portland Trail Blazers,82,36,46,0.439,3956,9093,3325,7396,45.0,...,2576,3671,1952,1309,678,433,453,1558,1581,-244
22,Phoenix Suns,82,36,46,0.439,3966,9317,3381,7075,47.8,...,2701,3484,2277,1153,593,392,329,1471,1509,-246
23,Toronto Raptors,82,30,52,0.366,3961,9091,3414,7462,45.8,...,2666,3700,2340,1257,664,348,484,1738,1484,-352
24,Philadelphia 76ers,82,24,58,0.293,3961,8988,3254,7168,45.4,...,2411,3263,1901,1117,752,366,420,1556,1530,-511
25,Brooklyn Nets,82,26,56,0.317,3956,8619,3086,7060,43.7,...,2493,3387,2063,1244,639,352,457,1698,1550,-583
26,Charlotte Hornets,82,19,63,0.232,3951,8618,3142,7308,43.0,...,2703,3706,1994,1271,607,368,435,1535,1488,-747
27,Utah Jazz,82,17,65,0.207,3961,9175,3305,7272,45.4,...,2741,3724,2093,1412,555,360,527,1549,1580,-766
28,New Orleans Pelicans,82,21,61,0.256,3951,9006,3332,7368,45.2,...,2583,3576,2119,1201,701,429,428,1499,1471,-773
29,Washington Wizards,82,18,64,0.220,3946,8856,3233,7371,43.9,...,2716,3583,2058,1276,623,420,428,1618,1490,-1020

In [71]:
team_wins_data = team_totals[['TEAM', 'W']].copy()

# --- Merge the DataFrames ---
# We'll merge based on the full team name ('TEAM' column), 
# assuming the names match reasonably well between the two DataFrames.
# Using how='left' ensures all rows from your final_team_stats are kept.

final_data_with_wins = pd.merge(
    final_team_stats, 
    team_wins_data,
    on='TEAM',  # Merge using the 'TEAM' column which should exist in both
    how='left'
)

final_data_with_wins.to_csv('../../data/cleandata/Cleaned_2024-2025TeamZonesLength.csv', index=False)